### ISSUE TITLE
Error when building font on Github Action

### ISSUE THREAD

**Issue by NNBnh** [avivace/iosevka-docker#13]
Hello, I have trying to automatically build the font with Github Action recently and I come up this this setting:

```yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Remove old build
        run: rm -rf dist

      - name: Build fonts
        run: docker run -it -v $(pwd):/build avivace/iosevka-build
```

<sub>[File's link](https://github.com/NNBnh/bmono/blob/bb25b5231500b4df5fa8c012f2de6583f67ce394/.github/workflows/main.yml)</sub>

But when run it show this error:

![image](https://user-images.githubusercontent.com/43980777/167346666-12fe6a9a-1b83-4786-b10f-5cce652efc83.png)

So I try to fix it:

```diff
        - name: Build fonts
-         run: docker run -it -v $(pwd):/build avivace/iosevka-build
+         run: docker run -i -v $(pwd):/build avivace/iosevka-build
```

Now it run for a bit but still exit without building:

![image](https://user-images.githubusercontent.com/43980777/167346774-87416526-b6f8-4fbd-857e-3d774f6fe5dd.png)

I'm still learning Docker so I'm not sure if this is a bug or I'm missing something, could you take a look please?
